ocaml-community/yojson

- Changes
- read.mll
The column position of the start column always seemed to be 2 more than the actual 0-indexed column. I'm not entirely certain of the reasoning behind the offsets but this appears to fix the problem for me. :-/
> Fix the beginning-of-error cnum off-by-2

- util.ml
- yojson.ml.cppo
- yojson.mli.cppo
Hi,
Is there a reason for the `Util` submodule to be defined only for the `Basic` variant?
In case there is not, here is a patch that adds a `Util` submodule to the `Safe` variant, similar to the one defined in `Basic`.
Thanks!
> Add a Yojson.Safe.Util module

- common.ml
- common.mli
- pretty.ml
- read.mli
- read.mll
- safe.mli
- write.ml
- write.mli
- write2.ml
- write2.mli
- yojson_biniou.ml
Should resolve #24. I also removed trailing spaces and tabs (can revert if you want).
Are there plans for making yojson and its dependencies `-safe-string` compatible?
> Cleanup and addition of a formatter function

- .gitignore
- Makefile
Generate cmt/cmti's by adding the -bin-annot flag and install them along
the mli's.
> Install cmt/cmti/mli's

- opam
E.g. you can now pin to a particular branch in this repo rather than
setting dev-repo. Also, this more accurately reflects the depeendencies
by specifying that ocamlfind is build only.
> Add local opam file for pinning

- Makefile
Checking for dynlink and correct file extensions manually is not
necessary as all of that information can come directly from `$(ocaml
-where)/Makefile.config`. It defines:
* `NATDYNLINK` which is true when dynlink is available
* `EXE` contains the platform specific extension for binaries
* `EXT_{LIB,OBJ}` contain platform specific lib/object extensions
Also, findlib installation is simplified to just use `$(wildcard ...)` to
select files to copy. wildcard is safe because it returns blank when the
targets aren't there.
Finally, there's no need to check for particularly binaries to install,
since we know what the name should be from `$(EXE)`.
> Makefile simplifications

- read.mll
When there is an invalid token consisting of one character followed by eof, `long_error` tries to print more than one character, which results in a failure.
```ocaml
Exception: Failure "lexing: empty token".
Exception: Yojson.Json_error "Line 1, bytes 0-2:\nInvalid token 'xx'".
```
I don't know whether there was a valid reason to look for more characters. If not, the fix is very easy.
> Fix lexing failure

- bench/jbuild
- bin/jbuild
- examples/jbuild
- lib/jbuild
Sorry, yet another safe-string related PR.. :/
It's just to enforce for future developments and also I realized the ```bytes``` dependency is pretty useless because yojson is only available only for OCaml >= 4.02 (where the ```Bytes``` module exists anyway).
> Enforce -safe-string

- lib/jbuild
Without this fix, there is an occasional build race on trying
to find `type.ml`:
```
Error: File "yojson.cppo.mli", line 43, characters 0-19
Error: Cannot find included file "type.ml"
```
Also remove a duplicate dependency on `type.ml` in the previous
rule as part of this PR.
Signed-off-by: Anil Madhavapeddy <anil@recoil.org>
> fix jbuild dependencies for cppo generation

- CHANGES.md
- lib/read.mli
- lib/read.mll
- lib/write.ml
Fixes #62 
I've been looking through the code to find other cases than the one mentioned in #61, mostly grep-ing `with` and `exception`.
It all seems good. I've noted two things that could eventually be swallowing exceptions but didn't want to take actions as they probably don't require one:
1. There are a bunch of `try ... with _ ->` which all surround single standard library function calls such as `int_of_string` or `List.nth`. It could eventually be narrowed to catching a specific exception as the doc specifies which one it's supposed to raise. The only thing that I imagine could go wrong is that it could catch a `Sys.Break` if enabled.
2. In [`read.mll`](https://github.com/mjambon/yojson/blob/master/lib/read.mll#L1151) if the finalizer passed to `stream_from_lexbuf` raises in the …
> Don't ignore exceptions

- CODEOWNERS
@NathanReb needs to be made a project member first (see https://github.com/ocaml-community/yojson/issues/68).
> Make @NathanReb the new default codeowner.

- .gitignore
- yojson.opam
I have a number of maintenance changes and thought that using the OPAM2 format might be a good point to start.
> Update opam file to OPAM 2 format

- .travis.yml
- README.md
As noticed, building on macOS takes forever and getting all the variations to build is 2h+ of waiting. Therefore I decided to exclude all but the newest OCaml for builds.
There is the questions whether it should not be enough to just test 4.02 and 4.07 on the Linux side since versions in between should just work, but these builds happen all faster than a single build on macOS.
> Reduce macOS builds

- bench/bench.ml
To inpect the performance impact of #74 it would be good to have benchmarks that stress the write performance more, so here's 3 benchmarks that write larger JSON values.
> Add benchmarks to test writing larger JSON

- CHANGES.md
- lib/type.ml
This has been causing troubles all around with no actual benefit.
> Revert deprecation warning on `json` type aliases

- yojson.opam
This directive results in failure when downgrading Dune versions, due to version-specific functionality in the Dune language. See https://github.com/ocaml/opam/issues/3850 for more details.
> opam: remove the 'build' directive on dune dependency

- .travis.yml
I got this trick from @lukepalmer, and it has sped up the builds of my project significantly. On my branch it took about 9-14 minutes per compiler to build the code, after rerunning the branch it took 2-7 minutes to build, which in my book is a significant life quality improvement.
> Enable caching of OPAM directory

- bench/bench.ml
This adds benchmarking for the functions that write to `out_channels`. Helpful for #74 where the underlying buffer is being replaced.
> Add channel benchmarks

- META.yojson.template
I stumbled upon some problems with the latest version due to this file. With this file the `dune-package` generated was wrong and looked like this:
````
(lang dune 2.0)
(use_meta)
(version 17dc47d)
````
And compiling [ppx_yojson_conv](https://github.com/janestreet/ppx_yojson_conv) failed with the error message :
````
File "<lib>/yojson/dune-package", line 3, characters 1-8:
3 | (version 17dc47d)
^^^^^^^
Error: Unknown field version
````
> Remove no longer needed template file.

- README.md
- lib/util.mli
This fixes the links to `atd`/`atdgen` to the current canonical location.
> Fix URL of atdgen/atd in the documentation

- lib/util.ml
- lib/util.mli
This is available since 4.01 and we support 4.02+ so it is natively available in every supported version. And was already deprecated before.
Since we're doing a 2.0.0 release, we might as well just drop it while at it. The impact is absolutely minimal since this operator would be used via `open` and if it is not in the module it will instead refer to the `|>` operator in `Pervasives`/`Stdlib`/`Core`. I don't expect any real code to be affected by this change.
> Remove deprecated |> operator

- CHANGES.md
- lib/dune
- lib/pretty.mli
- lib/type.ml
I've also chose to remove `json_max`. A quick search on GitHub has not shown any usage of it (mind you, the search is very bad, so I possibly missed something).
Closes #97.
> Remove `json` type

- .github/workflows/changelog.yml
This is currently the branch that this repo uses as default.
> Run changelog action against `master` branch

- CHANGES.md
This happened but afterwards the type got removed altogether and the change was never released so mentioning it it the changelog is more confusing than helpful.
> Remove entry from changelog

- CHANGES.md
- lib/write.ml
- lib/write.mli
- test/fixtures.ml
- test/fixtures.mli
- test/test_write.ml
The POSIX standard requires that text files end with new lines, see the POSIX definition of [text files](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_403) and [lines](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206), or this [stackoverflow answer](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795#729795).
This was requested in #109. 
To give the possibility to keep the old behaviour, this PR adds an optional boolean parameter `newline` to the function `to_string` to specify whether a newline should be added or not. 
The default value is `true`, which is a breaking change, but `2.0` is anyway a breaking release.
> Making `to_string` generate POSIX-compliant files

- CHANGES.md
- lib/common.ml
- lib/pretty.ml
- lib/write.ml
This fixes #121.
Unfortunately no tests to add; as it stands, there's a only a single monolithic test for pretty-printing, and the simple change doesn't seem to warrant setting up a new harness.
> remove restriction against generating JSON with an atomic root value

- lib/yojson.cppo.mli
Adding the comment above `module Util` includes a description of the module on the main page of Safe, Raw and Basic.
Added the clarification of `Safe` usage of native OCaml int sizing.
> Minor documentation fomatting changes.

- README.md
The code is inspired by the identical badge from dune-release, adapting for the URLs and branch.
> Switch badge to point to OCaml CI

- CHANGES.md
- lib/pretty.ml
- lib/write2.ml
- lib/yojson.cppo.ml
- lib/yojson.cppo.mli
While removing `json` I came across `json_max` and wondered what that is for. So when I deleted it, I figured out it works this way:
- There is a top-level `Yojson` module which has a type `t`, that contains all the variants.
- That module has another module, `Yojson.Pretty` which has the prettyprinter for the "biggest" type.
- All the `Yojson.{Basic,Safe,Raw}` variants upcast their `t` type to this biggest type and and then use the functions from `Yojson.Pretty`.
- (Amusingly, it is therefore possible to get a `` `String`` in a variant that does not define `STRING` on the CPPO level, since it always uses `` `String`` instead of `` `Stringlit``, though this is mostly a weird behaviour and probably not a bug)
This PR changes it in a way that every of the variants has its own `Pretty` …
> Remove `json_max` type

- CHANGES.md
- lib/read.mll
As mentioned in #85 by @skcho, the code in `map_ident`/`map_string` was changed to not copy the whole buffer and give a start/end point (though this happened somewhat more on the accidental than deliberate side) thus subtly changing the semantics of the data `f` was called on. This saves copying but prevents `f` from peeking beyond the borders it was
assigned. Whether this breaks consumers depends on what they do with it.
Nevertheless, what this PR does is it applies the same logic to `map_lexeme`, so while the semantics might have changed at least they change in a consistent way.
Closes #85
> Avoid full buffer copy in `map_lexeme`

- doc/dune
- doc/index.mld
- lib/yojson.cppo.mli
This PR adds an `index.mld` to improve the entry point of the documentation.
It allows to:
- Hide packages that we do not want to include in the doc (such as `yojson-bench`)
- Describe the library in a short page, without the details of the API.
I think that it solves #112 and #44.
> Improved the entry point of the documentation.

- CHANGES.md
- lib/write.ml
- test/test_write.ml
Fixing `stream_to_file` bugs reported by @tcoopman in https://github.com/ocaml-community/yojson/pull/131#issuecomment-1034114373. The first commit is a clear bugfix (without it, the function is completely broken; I think it has been since 931050073020064a2182e659fd8d09f8a7e8240f), the second is rather an improvement in behavior -- the memory usage of the `stream_to_{file,channel}` functions now corresponds to the size of the largest element in the stream, instead of the total size of all elements of the stream.
> Stream fixes

- CHANGES.md
- bench/bench.ml
- bin/ydump.ml
- lib/dune
- lib/read.mli
- lib/read.mll
- lib/write.ml
- lib/write.mli
- test/test_write.ml
- yojson.opam
Before:
```
┌─────────────────────────────────────┬──────────┬────────────┬────────────┬──────────┬────────────┐
│ Name                                │ Time/Run │    mWd/Run │   mjWd/Run │ Prom/Run │ Percentage │
├─────────────────────────────────────┼──────────┼────────────┼────────────┼──────────┼────────────┤
│ JSON stream roundtrip               │ 998.06us │ 70_051.93w │ 10_985.58w │   13.98w │    100.00% │
└─────────────────────────────────────┴──────────┴────────────┴────────────┴──────────┴────────────┘
```
After:
```
┌────────────────────┬──────────┬────────────┬────────────┬──────────┬────────────┐
│ Name               │ Time/Run │    mWd/Run │   mjWd/Run │ Prom/Run │ Percentage │
├────────────────────┼──────────┼────────────┼────────────┼──────────┼────────────┤
│ JSON seq …
```
> Stream to Seq

- CHANGES.md
- lib/write.ml
- lib/write.mli
The handling of `?buf` parameters today makes little sense:
- `to_string` and all `stream_*` functions clear the buffer before
using it (so: they guarantee that they work in the same way no
matter what the input state of the buffer is, and they make no
guarantees on its output state)
- but `to_channel` and `to_output` make weird claims about it in the
documentation, that don't make sense to me, and appear to *not* clear
the buffer and in fact include, in their output, the content of the
buffer as it is passed.
I believe that the reason for this difference comes from the previous
codebase using Biniou, that was replaced by Buffer in
931050073020064a2182e659fd8d09f8a7e8240f
The change left the usage of ?buf in `to_channel` and `to_output`
rather incoherent (and I think broke the …
> lib/write: more regular usage protocol for ?buf parameters

- CHANGES.md
- bench/bench.ml
- bench/dune
Since I was curious myself how much of a difference it makes to provide a buffer instead of letting Yojson create one (cc @c-cube).
The results on current `master` are as follows:
```
Estimated testing time 20s (2 benchmarks x 10s). Change using '-quota'.
┌───────────────────────────────────┬──────────┬─────────┬────────────┬──────────┬────────────┐
│ Name                              │ Time/Run │ mWd/Run │   mjWd/Run │ Prom/Run │ Percentage │
├───────────────────────────────────┼──────────┼─────────┼────────────┼──────────┼────────────┤
│ JSON writing with internal buffer │ 594.23us │ 20.02kw │ 32_269.74w │    1.74w │    100.00% │
│ JSON writing with provided buffer │ 498.96us │ 20.02kw │     -3.90w │    0.70w │     83.97% │
└───────────────────────────────────┴──────────┴─────────┴────── …
```
> Add benchmark for running `to_channel` with a preallocated buffer

- CHANGES.md
- lib/write.ml
- lib/write.mli
- test/test_write.ml
At the moment the documentation claims that what we output is newline separated (which it isn't). As such we should probably either fix the documentation or the implementation.
In this PR I chose to go for the second thing. @panglesd added a way to configure whether a newline is added or not in #124 but since 2.0.0 is not yet released I thought it would be nice to generalize it to all the functions, especially if people don't want the separators.
I chose `sep` as the name of the argument, because it is a common name. Notably though it is different from `sep` as used in `Fmt` in that it is always generated in the end. The reason for this is that the semi-official ndjson spec specifies that the JSON always ends with a newline so having `~sep:"\n"` achieves exactly that behavior.
> Add a configurable `suf` separator

- CHANGES.md
- lib/read.mli
- lib/read.mll
It doesn't do much and made only sense in atdgen when we used to have a `json` type. Now that the type doesn't exist it would require to be renamed into `validate_t` but such functionality doesn't seem to make sense to exist in Yojson, especially as it never does any validation to begin with.
This issue was brought up by @metanivek in #136 and my assumption is that if we're changing the API then this function has no reason to exist and validation should be done on the atdgen side.
> Remove `validate_json`

- bench/bench.ml
- bench/dune
- yojson-bench.opam
In Core v0.15 `Command.run` is deprecated in favor of `Command_unix` to be able to split Unix parts into their separate packages. This means the code needs to adapt. Turns out v0.14 supports that already and since this is a benchmarking binary there isn't that much value in keeping it installable on large range of versions of Core.
> Use `Command_unix` following the deprecation of `Command`

- CHANGES.md
- lib/common.mli
- lib/read.mli
- lib/util.mli
- lib/write.ml
- lib/write.mli
- lib/write2.mli
Primarily makes it explicit that parsing errors raise `Json_error`, which isn't on the same page as parsing functions and didn't have any description. Surprisingly, serialization may also raise it in a corner case.
Secondarily, I reviewed all other raised exceptions to consistently document those as well (using `@raise`).
> Expand documentation of exceptions

- CHANGES.md
- lib/write.ml
- lib/write.mli
Removes the two unused functions according to the discussion in https://github.com/ocaml-community/yojson/pull/148#discussion_r923138077.
Notably, they are in the interface, but hidden from documentation and according to [sherlocode](https://sherlocode.com/?q=write_float_fast) no opam package calls them. This is unlike `write_float_prec` and `write_std_float_prec`, which are used by atdgen.
I'm not sure of why the fast versions exist in the first place though. Could be considered related to #51, but that seems to concern another issue.
> Remove `write_float_fast` and `write_std_float_fast`

- CHANGES.md
- lib/read.mll
- test/fixtures.ml
- test/fixtures.mli
- test/test_read.ml
- test/testable.ml
- test/testable.mli
When running `make test` in atd, which just switched to yojson 2.0.x, we get an out-of-bounds error on two unit tests:
```
$ make test
...
> [FAIL]        atdgen         34   test ambiguous record with json adapters.
[FAIL]        atdgen         35   test wrapping of polymorphic types.
...
┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        atdgen         34   test ambiguous record with json adapters.  │
└──────────────────────────────────────────────────────────────────────────────┘
[invalid] out-of-bounds substring position or length: string = "ambiguous", requested position = 1, requested length = 9
Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
Called from Dune__exe__Test_ambiguous_record_j.read_ambiguous.f in …
```
> Fix out-of-bounds error in atdgen parsers

- Makefile
- bench/conversions.ml
- bench/dune
- dune-project
- lib/dune
- test/compliance/dune
- test/dune
- test/pretty/dune
- yojson-bench.opam
- yojson.opam
Hey all,
This PR aims at using the Github application [current-bench](https://github.com/marketplace/ocaml-benchmarks) on yojson. All results are directly pulled from original benchmarks made using `Core_bench`, and none of that code has to change in the future.
Due to how current-bench works, I had to hijack the `make bench` rule in the Makefile, but the old box-printing command is still available at `make bench-local`.
To fully activate the gh app you'll need to install it on the github marketplace.
> Allow continuous benchmarking with current-bench

- .git-blame-ignore-revs
- .ocamlformat
- .ocamlformat-ignore
- bench/bench.ml
- bin/ydump.ml
- dune-project
- examples/filtering.ml
- lib/common.ml
- lib/common.mli
- lib/monomorphic.mli
- lib/read.mli
- lib/safe.ml
- lib/safe.mli
- lib/util.ml
- lib/util.mli
- lib/write2.ml
- lib/write2.mli
- test/compliance/test.ml
- test/fixtures.ml
- test/fixtures.mli
- test/pretty/atd.ml
- test/pretty/test.ml
- test/test.ml
- test/test_monomorphic.ml
- test/test_read.ml
- test/test_write.ml
- test/testable.ml
This enables `ocamlformat` on the subset of the codebase that does not use CPPO.
> Enable `ocamlformat` on the part of the codebase that doesn't use CPPO

- CHANGES.md
- lib/util.ml
- lib/yojson.cppo.ml
- lib/yojson.cppo.mli
Fix for https://github.com/ocaml-community/yojson/issues/96
> Raw.Util module CPP

- .ocamlformat-ignore
#163 created a CI failure, this should fix it.
(Hope to get rid of CPPO in the long term, but this is how it is for now)
> Make `ocamlformat` ignore files using CPPO

- CHANGES.md
- lib/util.ml
- lib/util.mli
- test/fixtures.ml
- test/test.ml
- test/test_util.ml
- test/test_util.mli
Allows recurisve access to nested object fields using a list of keys
> Add path function

- lib/dune
- lib/lexer_utils.mll
- lib/read.mll
The forward ref make jsoo deadcode elimination ineffective.
Fix #84 to some degree.
> Remove forward ref in the lexer

- CHANGES.md
- lib/lexer_utils.mll
- lib/read.mll
- test/test_read.ml
Added a test that currently fails, to highlight the problem raised in #171.
> Added failing test on parsing failure

- CHANGES.md
- dune-project
- lib/dune
- lib/mucppo/dune
- lib/mucppo/mucppo.ml
- yojson.opam
This removes a build dependency and replaces the conditional compilation with a mucppo, a CPPO subset meant for embedding in builds: https://github.com/Leonidas-from-XIV/mucppo
The advantage is that it sheds another dependency from Yojson and given it is only needed at compile time, the tool is quickly built (as it is a single file) and never installed into the users switch.
> Replace CPPO with µCPPO

- bin/ydump.ml
- lib/lexer_utils.mll
- lib/read.mll
- lib/write.ml
- test/test_read.ml
This adds a few regression tests to make sure the printing of error location doesn't break when working on the code. One of the tests shows even that the printing is off and needs to be fixed, so I marked it that it is buggy (and might push a fix for it later, but I feel this is already useful as-is).
> Error printing tests

- dune-project
- yojson-five.opam
In https://github.com/ocaml/opam-repository/pull/25994 I realized that `yojson-five` does not depend on `yojson` in the OPAM metadata. This fixes the issue. The constraint on the version is technically speaking not necessary, but for keeping our own sanity in determining the version bounds it is easier to do it this way.
> Add proper dependency from `yojson-five` to `yojson`

- test/fixtures.ml
- test/fixtures.mli
- test/test_read.ml
It seems to work fine so this PR just adds a test that this is the case.
Closes #155
> Add test for handling CRLF line endings

- dune-project
- yojson-bench.opam
- yojson-five.opam
- yojson.opam
Instead of writing our own docs to github pages, pointing to ocaml.org is kind of nicer.
> Use ocaml.org as documentation location

- CHANGES.md
- lib/json5/errors.ml
- lib/json5/errors.mli
- lib/json5/lexer.ml
- lib/json5/parser.ml
- test_json5/test.ml
Since JSON5 is a standard intended to parse JSON written by humans, it's a bit unfortunate that the error messages were not very descriptive.
I tried to make them closer to the ones displayed by the classic YoJson parser. Also, when it's available, the line where the error message is located is displayed.
> Improve the error messages displayed by the JSON5 lexer and parser.

- CHANGES.md
- lib/json5/unescape.ml
- test_json5/test.ml
According to the specification https://spec.json5.org/#escapes , as far as I understand : 
- `\'` should be `'` in the returned string (not `\'`)
- `\"` should be `"` (not `\"`)
- and other characters should be returned without the leading backslash too (e.g., `\a` -> `a`)
However, I did not understand what happened for `\1` to `\9`, so I kept the former behavior: rejecting the escape sequence.
> JSON5: fix escape sequences
